title: Sybelle cosmetics
author: Panoramedia
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Simple Static Site

twitter_username: macrod68
github_username: macrod68

sass:
  style: compressed
