title: Sybelle cosmetics
author: Panoramedia
email: contact@domoti.fr
description: > # this means to ignore newlines until "baseurl:"
  A Simple Static Site

twitter_username: macrod68
github_username: macrod68

sass:
  style: compressed
  # plugin
# This will require each of these plugins automatically.
# plugins: ['jekyll-lunr-js-search']
# gems: ['jekyll-lunr-js-search']
