title: Sybelle cosmetics
author: Domoti
email: contact@domoti.fr
description: > # this means to ignore newlines until "baseurl:"
  Sybelle Votre parenthèse beauté

twitter_username: domtwit
github_username: domgit

baseurl: '/' # the subpath of your site, e.g. /blog
url: 'http://www.sybelle.fr' # the base hostname & protocol for your site, e.g. http://example.com

include: ['_pages']
exclude: ['README.md']
# exclude: [css, _sass, 'README.md']

sass:
  # style: compressed :nested :compact :expanded :compressed
  # @see https://web-design-weekly.com/2014/06/15/different-sass-output-styles/
  style: expanded
  sass_dir: _sass
  sourcemap: true
# plugin
# This will require each of these plugins automatically.
# plugins: ['jekyll-lunr-js-search']
# gems: ['jekyll-lunr-js-search']
